#!/bin/sh
#
# Run this shell script to bootstrap as necessary after a fresh checkout.

autoreconf -i
rm -rf autom4te.cache

# Generate manual pages.
version=`grep '^kadmin-remctl' NEWS | head -1 | cut -d' ' -f2`
pod2man --release="$version" --center="kadmin-remctl" ksetpass.pod \
    > ksetpass.1
pod2man --release="$version" --center="kadmin-remctl" passwd_change.pod \
    > passwd_change.1
pod2man --release="$version" --center="kadmin-remctl" --section=8 \
    kadmin-backend > kadmin-backend.8
pod2man --release="$version" --center="kadmin-remctl" --section=8 \
    kadmin-backend-heim > kadmin-backend-heim.8
